version: '3.8'

services:
  webapifordocker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # Uncomment the following lines if you want to mount local code for hot-reload (development only)
    # volumes:
    #   - ./WebApiForDocker:/app
